backend:
  name: github
  repo: ajudafacity/manualfacity  # Substitua pelo seu usuário e repositório
  branch: main
  # base_url: https://api.netlify.com
  # auth_endpoint: https://api.netlify.com
  site_id: c56f02b1-db2e-4082-ad6b-350889284ce3
 

media_folder: "static/img" # Pasta para armazenar imagens
public_folder: "/img"

site_url: "https://manualfacity.netlify.app/"  # Substitua pela URL do seu site

collections:
  - name: "docs"
    label: "Documentação"
    folder: "docs"
    create: true
    nested:
      depth: 3  # Permitir a criação de subpastas até 2 níveis
    slug: "{{fields.categoria}}/{{fields.title}}"  # Cria o slug baseado na categoria (pasta) e no título
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "string", hint: "Digite o nome da pasta ou subpasta (ex: tutorial-basics)" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
