backend:
  name: github
  repo: ajudafacity/manualfacity  # Substitua pelo seu usuário e repositório
  branch: main
  base_url: https://api.netlify.com
  site_id: c56f02b1-db2e-4082-ad6b-350889284ce3
  auth_endpoint: https://api.netlify.com
 

media_folder: "static/img" # Pasta para armazenar imagens
public_folder: "/img"

site_url: "https://manualfacity.netlify.app/"  # Substitua pela URL do seu site

collections:
  - name: "docs"
    label: "Documentação"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
