backend:
  name: github
  repo: ajudafacity/manualfacity  # Substitua pelo seu usuário e repositório
  branch: main
  # base_url: https://api.netlify.com
  # auth_endpoint: https://api.netlify.com
  site_id: c56f02b1-db2e-4082-ad6b-350889284ce3
 

media_folder: "static/img" # Pasta para armazenar imagens
public_folder: "/img"

site_url: "https://manualfacity.netlify.app/"  # Substitua pela URL do seu site

collections:
  - name: "docs"
    label: "Documentação"
    folder: "docs"  # Diretório principal de documentos
    create: true
    slug: "{{fields.slug}}"  # Utilizando o campo slug para criar o nome dos arquivos
    nested:
      depth: 10  # Permitir criar subpastas até 10 níveis
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Nome do arquivo, sem espaços" }
      - { label: "Categoria", name: "categoria", widget: "string", hint: "Nome da pasta ou subpasta" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }