backend:
  name: github
  repo: ajudafacity/manualfacity  # Substitua pelo seu usuário e repositório
  branch: main
  # base_url: https://api.netlify.com
  # auth_endpoint: https://api.netlify.com
  site_id: c56f02b1-db2e-4082-ad6b-350889284ce3
 

media_folder: "static/img" # Pasta para armazenar imagens
public_folder: "/img"

site_url: "https://manualfacity.netlify.app/"  # Substitua pela URL do seu site

collections:
  - name: "docs"
    label: "Documentação"
    folder: "docs"
    create: true
    nested:
      depth: 5  # Permitir criação de subpastas até 5 níveis
    slug: "{{fields.categoria}}/{{slug}}"  # Usar o campo 'categoria' e 'slug' para o caminho do arquivo
    fields:
      - { label: "Título", name: "title", widget: "string" }  # Campo de título do documento
      - { label: "Categoria/Pasta", name: "categoria", widget: "string", hint: "Digite o caminho da pasta (ex: pasta1/pasta2)" }  # Campo para o caminho da pasta
      - { label: "Slug", name: "slug", widget: "string", hint: "Slug é o nome amigável do arquivo" }  # Nome final do arquivo
      - { label: "Conteúdo", name: "body", widget: "markdown" }  # Campo para conteúdo em markdown