backend:
  name: github
  repo: ajudafacity/manualfacity  # Substitua pelo seu usuário e repositório
  branch: main
  # base_url: https://api.netlify.com
  # auth_endpoint: https://api.netlify.com
  site_id: c56f02b1-db2e-4082-ad6b-350889284ce3
 

media_folder: "static/img" # Pasta para armazenar imagens
public_folder: "/img"

site_url: "https://manualfacity.netlify.app/"  # Substitua pela URL do seu site

collections:
  - name: "docs"
    label: "Documentação"
    folder: "docs"  # Diretório principal onde as pastas serão criadas
    create: true
    nested: true  # Ativa a navegação por pastas
    identifier_field: "slug"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "string", hint: "Nome da pasta (categoria)" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
    meta: { folder: "{{categoria}}/{{slug}}" }
