backend:
  name: github
  repo: ajudafacity/manualfacity  # Substitua pelo seu usuário e repositório
  branch: main
  # base_url: https://api.netlify.com
  # auth_endpoint: https://api.netlify.com
  site_id: c56f02b1-db2e-4082-ad6b-350889284ce3
 

media_folder: "static/img" # Pasta para armazenar imagens
public_folder: "/img"

site_url: "https://manualfacity.netlify.app/"  # Substitua pela URL do seu site

collections:
  - name: "docs"
    label: "Documentação"
    folder: "docs/{{slug}}"  # Diretório dinâmico com base no slug
    create: true
    nested:
      depth: 3  # Permitir subpastas até 3 níveis
    slug: "{{fields.categoria}}/{{slug}}"  # O slug será baseado na categoria e no título
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "string", hint: "Digite o nome da pasta" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Digite o slug para a URL" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }